_BASE_: "Base-CRCNN-COCO.yaml"
MODEL:
  META_ARCHITECTURE: "UnifiedRCNN"
  ROI_HEADS:
    NUM_CLASSES: 722
    NAME: "UnifiedCascadeROIHeads"
  ROI_BOX_HEAD:
    USE_SIGMOID_CE: True
    # USE_EQL_LOSS: True
    HIERARCHY_IGNORE: True
    HIERARCHY_POS_PARENTS: True
DATASETS:
  TRAIN: ("objects365_train","coco_2017_train","oid_train","mapillary_960_train")
  TEST: ("coco_2017_val", "objects365_val", "oid_val_v2_expanded","mapillary_val")
  # TEST: ('voc_cocoformat_test','viper_val', 'scannet_val','wilddash_public',
  #   'kitti_train','crowdhuman_val', 'cityscapes_cocoformat_val',)
DATALOADER:                                                                                                                                                                                                                                                                                                                                                                 
  SAMPLER_TRAIN: "MultiDatasetSampler"
  NUM_WORKERS: 1
MULTI_DATASET:
  ENABLED: True
  DATASETS: ['objects365', 'coco', 'oid', 'mapillary']
  NUM_CLASSES: [365, 80, 500, 37]
  DATA_RATIO: [1, 1, 1, 1]
  USE_CAS: [True, False, True, False]
  UNIFIED_LABEL_FILE: 'datasets/label_spaces/learned_mAP+M.json'
  # MATCH_NOVEL_CLASSES_FILE: 'datasets/label_spaces/mAP_val+M_722_4d_labelmap_test.json'
  # UNIFIED_EVAL: True
  # UNIFIED_NOVEL_CLASSES_EVAL: True
  # UNIFY_LABEL_TEST: False
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  STEPS: (160000,)
  MAX_ITER: 180000